# MIT Licensed theme: https://github.com/nandomoreirame/end2end
# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
plugins:
  - jekyll-seo-tag
  - jekyll-gist
#
paginate: 3
paginate_path: "/blog/page/:num/"
comments: true
#
source: 
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded
#
timezone:           Europe/Munich
locale:             en_US
#
# SEO settings
title: "Sadiq Huq"
description: "A blog on Computational Mechanics"
keywords: "FEA, CAE, CFD, turbulence, computational, mechanics, deep, machine, learning, data, science, artificial, intelligence"
url: https://sadiqhuq.github.io
baseurl: ""
# baseurl: "/sh"
host: 0.0.0.0
#
google_analytics: UA-87654273-1
repo: http://github.com/sadiqhuq/sadiqhuq.github.io
disqus_shortname: "huq"
disqus_site_shortname: "huq"
#
# Author settings
author:
  name      : Sadiq Umar Abdul Huq
  nameshort : Sadiq Huq
  job       :
   EN       : Computational Mechanics Engineer
   DE       : "Berechnungsingenieur"
   TA       : "கணக்கீட்டு இயக்கவியல் பொறியாளர்"
   DETA     : "Berechnungsingenieur | கணக்கீட்டு இயக்கவியல் பொறியாளர்"
  bio       : 
  thumb     : /images/webpage/avatar.jpg
# email     : 
# url       : 
  github    : http://github.com/sadiqhuq
  twitter   : http://twitter.com/comflics
  kaggle    : http://kaggle.com/sadiqhuq
  linkedin  : http://linkedin.com/in/sadiqhuq
  xing      : https://www.xing.com/profile/Sadiq_Huq
  youtube   : https://www.youtube.com/user/comflics/videos
  stackoverflow: http://stackoverflow.com/users/711499/sadiq-huq 
#
# navbar pages
navbar:
  - slug: cv
    title: CV
  - slug: blog
    title: Blog
#
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
#
